### Register
POST http://localhost:9080/api/register
Content-Type: application/json

{ "nome" : "Mario",
  "cognome" : "Rossi",
  "targa" : "AB123CD",
  "email" : "prova@gmail.com",
  "password" : "papopepo" }

### Login
POST http://localhost:9080/api/login
Content-Type: application/json

{ "email" : "prova@gmail.com",
  "password" : "papopepo" }

> {%
    client.global.set("token", response.body.token);
%}

### Get All Parcheggi
GET http://localhost:9080/api/park

### Get Parcheggio
GET http://localhost:9080/api/park/1

### Get Parcheggi disponibili in un intervallo
GET http://localhost:9080/api/park/available/2026-04-26%2018:00:00/2026-04-26%2019:00:00

### Get Profilo
GET http://localhost:9080/api/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{ "email" : "prova@gmail.com" }

### Put Prenotazione
PUT http://localhost:9080/api/reservation
Authorization: Bearer {{token}}
Content-Type: application/json

{ "start_time" : "2026-04-22 18:00:00",
  "end_time" : "2026-04-22 19:00:00",
  "id_parking_lot" : 1 }

### Get Prenotazione
GET http://localhost:9080/api/reservation/search-user
Authorization: Bearer {{token}}

> {%
    client.global.set("id_prenotazione", response.body.uuid);
%}

### Delete Prenotazione
DELETE http://localhost:9080/api/reservation
Authorization: Bearer {{token}}
Content-Type: application/json

{ "id" : "18730f83-3e2e-11f1-9fde-56a82e5ca73b" }

### Post Logout
POST http://localhost:9080/api/logout
Authorization: Bearer {{token}}

### Accesso ad una rotta protetta + con autorizzazione
PUT http://localhost:9080/api/park
Authorization: Bearer {{token}}